version: "3.8"

volumes:
    db:

services:
    db:
        image: "postgres"
        restart: always
        environment:
            #I hope this is only exposed locally...
            POSTGRES_PASSWORD: "secret"
            POSTGRES_USER: "musicserver"
        volumes:
            - db:/var/lib/postgresql/data
    
    #ONLY ENABLE WHEN DEBUGGING DO NOT LEAVE EXPOSED!!
    #adminer:
    #        image: adminer
    #        restart: always
    #        ports:
    #                - 8080:8080
    #        depends_on:
    #                - db

    musicserver:
        image: "musicserver"
        environment:
            secret: "jl-7cir&r7zcj-w2)ox$$^!j5$$j=hj=rdh!euv+a73h5zjt*bri"
            dbname: "db"
            dbuser: "musicserver"
            dbpass: "secret"
        #TODO: add proper volumes
        depends_on:
            - db
        volumes:
            - ./deployproxy/media:/root/deployproxy/media
            - ./deployproxy/static:/root/deployproxy/static


    deployproxy:
        image: "deployproxy"
        ports:
            - 8000:80
        depends_on:
            - musicserver
        volumes:
            - ./deployproxy/media:/etc/static/media
            - ./deployproxy/static:/etc/static/static