version: "3.8"

volumes:
    db:
    keys:

services:
    db:
        image: "postgres"
        restart: always
        environment:
            POSTGRES_PASSWORD: ${dbpass}
            POSTGRES_USER: "musicserver"
        volumes:
            - db:/var/lib/postgresql/data
    
    #ONLY ENABLE WHEN DEBUGGING DO NOT LEAVE EXPOSED!!
    #adminer:
    #        image: adminer
    #        restart: always
    #        ports:
    #                - 8080:8080
    #        depends_on:
    #                - db

    musicserver:
        image: "musicserver"
        build: .
        environment:
            #set secret enviornment variable (I recommend https://djecrety.ir/)
            secret: ${secret}
            dbname: "db"
            dbuser: "musicserver"
            dbpass: ${dbpass}
        depends_on:
            - db
        volumes:
            - ./deployproxy/media:/root/deployproxy/media
            - ./deployproxy/staticfiles:/root/deployproxy/staticfiles
            - keys:/root/keys

    deployproxy:
        image: "deployproxy"
        build: ./deployproxy
        ports:
            - 8000:80
            - 8443:443
        depends_on:
            - musicserver
        volumes:
            - ./deployproxy/media:/etc/static/media
            - ./deployproxy/staticfiles:/etc/static/static
            - ./certs:/etc/certs