# Generated by Django 3.0.6 on 2020-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200522_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songfile',
            field=models.FileField(max_length=50, upload_to='media/songs/'),
        ),
    ]
