# Generated by Django 3.0.6 on 2020-06-09 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200608_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='songfile',
        ),
    ]
