# Generated by Django 3.0.6 on 2020-06-09 01:00

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_song_songfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=50, validators=[homepage.models.isfilesafe]),
        ),
    ]
