# Generated by Django 3.0.7 on 2020-06-16 23:36

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200608_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=50, unique=True, validators=[homepage.models.isfilesafe]),
        ),
    ]
