# Generated by Django 3.0.7 on 2020-06-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200616_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
    ]
