# Generated by Django 3.0.7 on 2020-06-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20200619_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=20),
        ),
    ]
