# Generated by Django 3.0.7 on 2020-07-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_song_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=20),
        ),
    ]
