name: "build docker image"

on: ["push"]

jobs:
    build:
        runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v2"
        - name: "build image"
        run: "docker build -t musicserver ."
        - name: "export image"
        run: "docker save --output musicserver.tar musicserver"
        - uses: "actions/upload-artifact@v2"
        with:
            name: "docker image"
            path: "musicserver.tar"